using Antlr4.Runtime.Atn;
using System.Collections.Generic;

namespace LoschScript.CodeAnalysis;

/// <summary>
/// Represents a code analyzer that analyzes a string of code.
/// </summary>
public class StringAnalyzer : IAnalyzer<string>
{
    /// <summary>
    /// Performs the analysis.
    /// </summary>
    /// <param name="source">The string to analyze.</param>
    /// <returns>The error messages generated by the analyzer.</returns>
    public virtual List<ErrorInfo> Analyze(string source) => new();
}