using Dassie.Data;
using System.Collections.Generic;

namespace Dassie.Extensions;

/// <summary>
/// Represents the behavior of the document transformer.
/// </summary>
public enum DocumentTransformMode
{
    /// <summary>
    /// The original document is overwritten by the transformed documents.
    /// </summary>
    Overwrite,
    /// <summary>
    /// The transformed documents are appended to the list of documents alongside the original one.
    /// </summary>
    Append
}

/// <summary>
/// Represents a document transformer.
/// </summary>
public interface IDocumentTransformer
{
    /// <summary>
    /// The name of the document transformer.
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// The glob pattern to match files to transform with.
    /// </summary>
    public string Pattern { get; }

    /// <summary>
    /// The mode the transformer operates in.
    /// </summary>
    public DocumentTransformMode TransformMode => DocumentTransformMode.Overwrite;

    /// <summary>
    /// The method that is called when a transformation is requested.
    /// </summary>
    /// <param name="inputDocuments">The input documents for the transformation.</param>
    /// <returns>The output documents generated by the transformer.</returns>
    public IEnumerable<Document> Transform(IEnumerable<Document> inputDocuments);
}