using Dassie.Text.Tooltips;

namespace Dassie.Messages;

/// <summary>
/// Represents a diagnostic message emitted by the compiler, such as an error message.
/// </summary>
public class MessageInfo
{
    /// <summary>
    /// The kind of error that the current <see cref="MessageInfo"/> instance represents.
    /// </summary>
    public MessageCode Code { get; set; }

    /// <summary>
    /// Supports custom error codes to be used by analyzers.
    /// </summary>
    public string CustomCode { get; set; }

    /// <summary>
    /// The text of the message.
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// The name of the document the message originates from.
    /// </summary>
    public string File { get; set; }

    /// <summary>
    /// The starting position of the message in the document.
    /// </summary>
    public (int Line, int Column) Location { get; set; }

    /// <summary>
    /// Specifies wheter or not to display the code location in the generated output.
    /// </summary>
    public bool HideCodePosition { get; set; }

    /// <summary>
    /// The length, in characters, of underlying code section the message refers to.
    /// </summary>
    public int Length { get; set; }

    /// <summary>
    /// The severity of the message.
    /// </summary>
    public Severity Severity { get; set; }

    /// <summary>
    /// The source of the message.
    /// </summary>
    public MessageSource Source { get; set; } = MessageSource.Compiler;

    /// <summary>
    /// A tooltip representing the message.
    /// </summary>
    public Tooltip ToolTip { get; set; }

    /// <summary>
    /// Advanced information about the message aiding the user in debugging the cause of an error.
    /// </summary>
    public string Tip { get; set; }

    /// <summary>
    /// Converts the message into a human-readable format.
    /// </summary>
    /// <returns>A friendly representation of the message.</returns>
    public override string ToString()
    {
        string code = Code == MessageCode.Custom ? CustomCode : Code.ToString().Split('_')[0];
        return $"{File}{(HideCodePosition ? "" : $" ({Location.Line},{Location.Column})")}: {Severity switch
        {
            Severity.Warning => "warning",
            Severity.Error => "error",
            _ => "message"
        }} {code}: {Text}\r\n";
    }
}

/// <summary>
/// Specifies the severity of a message.
/// </summary>
public enum Severity
{
    /// <summary>
    /// An informative message.
    /// </summary>
    Information,
    /// <summary>
    /// A warning message.
    /// </summary>
    Warning,
    /// <summary>
    /// An error message.
    /// </summary>
    Error,
    /// <summary>
    /// A diagnostic build log message that is not caused by an error in the code.
    /// </summary>
    BuildLogMessage
}

/// <summary>
/// Specifies the source of a message.
/// </summary>
public enum MessageSource
{
    /// <summary>
    /// Specifies that a message was generated by the compiler.
    /// </summary>
    Compiler,
    /// <summary>
    /// Specifies that a message was generated by an analyzer.
    /// </summary>
    Analysis,
    /// <summary>
    /// Specifies that a message was generated by an external tool.
    /// </summary>
    External
}