global using Dassie.Helpers;
global using static Dassie.CodeGeneration.Api.Compiler;
global using static Dassie.CodeGeneration.Helpers.EmitHelpers;
global using static Dassie.Constants;
global using static Dassie.Errors.ErrorKind;
global using static Dassie.Errors.ErrorWriter;
global using static Dassie.Meta.FileContext;
global using static Dassie.Meta.MethodContext;
global using static Dassie.Meta.ProgramContext;
global using Directory = System.IO.Directory;
global using DirectoryInfo = System.IO.DirectoryInfo;
global using File = System.IO.File;
global using Path = System.IO.Path;
global using SearchOption = System.IO.SearchOption;